server:
  forward-headers-strategy: FRAMEWORK
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

spring:
  application:
    name: centralres
  profiles:
    active: dev
  config:
    import: optional:file:.env.properties[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

app:
  reservation:
    buffer-before-minutes: 10
    buffer-after-minutes: 15
  tax:
    rate: 0.18
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600000 # 1 hora
    refresh-token-expiration: 1209600000 # 14 dias
  file:
    allowed-extensions: [".jpg", ".jpeg", ".png", ".pdf", ".mp4", ".mp3"]
    allowed-folders: ["products", "profiles", "general"]
    max-size: 15MB
  frontend:
    url: http://localhost:4200 
  cors:
    allowed-origins: http://localhost:4200

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

niubiz:
  api:
    security: https://apisandbox.vnforappstest.com/api.security/v1/security
    session: https://apisandbox.vnforappstest.com/api.ecommerce/v2/ecommerce/token/session
    authorization: https://apisandbox.vnforappstest.com/api.authorization/v3/authorization/ecommerce
  merchant:
    id: ${NIUBIZ_MERCHANT_ID}
    user: ${NIUBIZ_USER}
    password: ${NIUBIZ_PASSWORD}