spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  frontend:
    url: http://localhost:4200
  cors:
    allowed-origins: http://localhost:4200