name: Backend CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Subir Imagen
        run: |
          # YA NO HACEMOS "cd backend" porque ya estamos ahí
          docker build -t ${{ secrets.DOCKER_USERNAME }}/central-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/central-backend:latest

deploy:
  needs: build-push
  runs-on: ubuntu-latest
  steps:
    - name: Desplegar en Google Cloud
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd central-app
          # Bajamos solo los cambios del backend
          docker-compose pull backend
          # Reiniciamos solo el backend
          docker-compose up -d backend
          # Limpiamos imágenes viejas
          docker image prune -f
