name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- TRABAJO 1: BACKEND ---
  build-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar c√≥digo
        uses: actions/checkout@v4

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Subir Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/central-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/central-backend:latest
