name: Backend CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Subir Imagen
        run: |
          # Construimos la imagen desde la raíz
          docker build -t ${{ secrets.DOCKER_USERNAME }}/central-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/central-backend:latest

  # --- FÍJATE AQUÍ: 'deploy' tiene 2 espacios de sangría para alinearse con 'build-push' ---
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en Google Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd central-app
            
            # 1. Bajamos solo la nueva imagen del backend
            docker-compose pull backend
            
            # 2. Reiniciamos solo el contenedor del backend
            docker-compose up -d backend
            
            # 3. Limpieza
            docker image prune -f